apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data-couchbase
  labels:
    app: data-couchbase
    env: dev
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi