debug : true
spring:
  application:
    name: product-api-service
server:
  port: 8080
app:
  couchbase:
    connection-string : couchbase://couchbase-master-service
    user-name : Admin
    password : test123
    primary-bucket : ProductTest

