debug : true
spring:
  application:
    name: product-api-service
server:
  port: 8080
app:
  couchbase:
    connection-string : couchbase://10.106.138.141,couchbase://couchbase-master-service
    user-name : Administrator
    password : password
    primary-bucket : product-data
    auto-index : true

