debug : true
spring:
  application:
    name: product-api-service
server:
  port: 8080
app:
  couchbase:
    connection-string : couchbase://couchbase-service
    user-name : Administrator
    password : password
    primary-bucket : default
    auto-index : true

