debug : true
spring:
  application:
    name: product-api-service
server:
  port: 8080
app:
  couchbase:
    bootstrap-hosts: couchbase-master-service
    #connection-string : couchbase://10.106.138.141
    user-name : Administrator
    password : password
    primary-bucket : product-data

