debug : true
spring:
  application:
    name: product-api-service
server:
  port: 8080
app:
  couchbase:
    connection-string : couchbase://10.106.138.141:30636
    user-name : Administrator
    password : password
    primary-bucket : product-data

