debug : true
spring:
  application:
    name: product-api-service
server:
  port: 8080
app:
  couchbase:
    connection-string : couchbase://10.103.22.7
    user-name : Administrator
    password : password
    primary-bucket : default
    auto-index : true

