debug : true
spring:
  application:
    name: product-api-service
server:
  port: 8080
app:
  couchbase:
    connection-string : couchbase://couchbase-master-service:8091
    user-name : Administrator
    password : password
    primary-bucket : product-data

